version: '3'
services:
  db:
    image: mysql/mysql-server:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'pierre'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'test'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootPassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  nextjs:
    build: ./
  nginx:
    build: ./nginx
    ports:
      - 80:80
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db: