version: '3'
services:
  db:
    image: mysql/mysql-server:8.0.21
    container_name: mySQL
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'team3'
      MYSQL_USER: 'pierre'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'rootPassword'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  nextjs:
    build: ./
    container_name: nextApp
  nginx:
    build: ./nginx
    container_name: mynginx    
    ports:
      - 80:80
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db: